services:
    contao_tcpdf.listener.print_article_as_pdf:
        class: Contao\TcpdfBundle\EventListener\PrintArticleAsPdfListener
        arguments:
            - "%kernel.project_dir%"
        tags:
        - { name: contao.hook, hook: printArticleAsPdf }
